version: '3.6'
services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./app:/app
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
      - influxdb
    environment:
      DB_USERNAME: root
      DB_PASSWORD: secret
      DB_HOST: mongodb # matches the service with mongodb

  mongodb:
    container_name: mongodb
    image: "percona/percona-server-mongodb:6.0.4" # If you reach and have Apple Silicon use: "percona/percona-server-mongodb:6.0.4-3-arm64"
    volumes:
      - ./docker/mongodb/data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: metrics
    ports:
      - "27017:27017"

  telegraf:
    container_name: telegraf
    image: telegraf:1.25-alpine
    volumes:
      - ./docker/telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mongodb
    env_file:
      - influxv2.env
    ports:
      - '8125:8125/udp'

  influxdb:
    container_name: influxdb
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    volumes:
      - ./docker/influxdbv2/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secure_password
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./docker/grafana/grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana: { }
  influxdbv2: { }
