{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "MongoDB Insert/Update Document",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mongodb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"document_inserted\" or r[\"_field\"] == \"document_updated\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"mongodb:27017\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"count\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"type\"] == \"insert\" or r[\"type\"] == \"update\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "PHP Code Memory Usage(Kb)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"request\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage\")\n  |> filter(fn: (r) => r[\"type\"] == \"update\" or r[\"type\"] == \"insert\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}